### ISSUE TITLE
Release version 2 to PyPI

### ISSUE THREAD

**Issue by greyhare** [django-cms/djangocms-modules#39]
In `django.utils.encoding`, [`force_text` was deprecated in Django 3.0](https://docs.djangoproject.com/en/4.2/releases/3.0/#django-utils-encoding-force-text-and-smart-text). It was replaced with `force_str` in Django 2.0.

I get this error when using this package with Django 4.2:

```
  File "/env/lib/python3.11/site-packages/djangocms_modules/cms_plugins.py", line 11, in <module>
    from django.utils.encoding import force_text
ImportError: cannot import name 'force_text' from 'django.utils.encoding' (/env/lib/python3.11/site-packages/django/utils/encoding.py)
```

It looks like this is only used in two files:

* `cms_plugins.py`
* `cms_toolbars.py`

**Comment by greyhare** [comment]
Patch: [force_str.patch](https://github.com/django-cms/djangocms-modules/files/12141335/force_str.patch)

Applied with `patch -p1 < force_str.patch` in the module directory. Works for me.

**Comment by fsbraun** [comment]
@greyhare Thank you for the patch! Can I interest you in creating a pull request?

**Comment by greyhare** [comment]
What else do I need in the pull request?

**Comment by fsbraun** [comment]
Extending the tests to current Django/Django CMS versions would be great!

**Comment by greyhare** [comment]
OK, this got weirder. **This issue is fixed** in commit 342c221 from last year. A chore for bumping version to 2.0.0.

Why is 1.0.0 the latest thing on PyPI?! That's what I'm getting:

```
$ ./venv/bin/pip index versions djangocms-modules
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
djangocms-modules (1.0.0)
Available versions: 1.0.0, 0.3.0, 0.2.0, 0.1.0
  INSTALLED: 1.0.0
  LATEST:    1.0.0
```

**Comment by fsbraun** [comment]
Hm. It seems like the `2.0.0` version was never actually released? (@marksweb : Do you remember why?).

So this might be the great point in time for djangocms-modules 2.0.0!

Things to update are:
* `CHANGELOG.rst`
* `djangocms-modules/__init__.py `(since 2.0.0 is not out, no change needed)
* `dj41_cms311.py`and `dj42_cms311.py` to be added in `tests/requirements/`
* `tox.ini` to reflect the changes in test requirements and cases
* `.github/workflows/test.yml` to be in sync with `tox.ini`

**Comment by greyhare** [comment]
No idea what to change in `CHANGELOG.rst`. Everything else was straightforward and passed `tox` so I pushed.

**Comment by marksweb** [comment]
@fsbraun @greyhare so looks like I did a few update bits for v2 and don't didn't finish releasing it?
I imagine wife/kids/life distracted me and I forgot that I'd not released it. 🤦‍♂️

**Comment by greyhare** [comment]
OK, so what's left to do?

**Comment by fsbraun** [comment]
I gues: Release it! 🎉. Thanks, @greyhare !
